services:
  ts-app:
    image: tailscale/tailscale:latest
    hostname: omnivore-label-bot
    container_name: ts-app
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - 'TS_EXTRA_ARGS=--advertise-tags=tag:container --reset'
      - TS_SERVE_CONFIG=/config/app.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./config:/config
      - ts-app:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: .nixpacks/Dockerfile
    restart: unless-stopped
    depends_on:
      - ts-app
    environment:
      - PORT=3000
      - REDISHOST=192.168.0.80
      - REDISPORT=6379
      - OMNIVORE_API_KEY=${OMNIVORE_API_KEY}
      - OMNIVORE_USER_ID=${OMNIVORE_USER_ID}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    network_mode: service:ts-app

volumes:
  ts-app:
    driver: local
