services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - omnivore-bot-network
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
    networks:
      - omnivore-bot-network
